// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(grunt) {
    grunt.initConfig({
      copy: {
        venders: {
          files: [
            {
              cwd: "src/venders",
              expand: true,
              src: ["**"],
              dest: "dev/venders"
            }
          ]
        }
      },
      sync: {
        main: {
          files: [
            {
              cwd: "src",
              src: "**/*.html",
              dest: "dev/"
            }, {
              cwd: "venders",
              src: "**/*.*",
              dest: "dev/"
            }
          ]
        }
      },
      connect: {
        options: {
          port: 9000,
          hostname: "0.0.0.0",
          base: "dev/"
        },
        livereload: {
          options: {
            open: false
          }
        }
      },
      watch: {
        js: {
          files: ["src/js/*.js", "src/js/**/*.js"]({
            tasks: ["concat:js"]
          })
        },
        css: {
          files: ["src/css/*.css"],
          tasks: ["concat:css"]
        },
        html: {
          files: ["src/views/*.html"],
          tasks: ["sync"]
        },
        index: {
          files: ["src/index.html"],
          tasks: ["sync"]
        },
        options: {
          livereload: true
        }
      },
      concat: {
        js: {
          src: ["src/js/app.js", "src/js/controllers/**/*.js"],
          dest: "dev/js/final.js"
        },
        css: {
          src: ["src/css/*.css"],
          dest: "dev/css/*.css"
        }
      }
    });
    grunt.loadNpmTasks("grunt-contrib-concat");
    grunt.loadNpmTasks("grunt-contrib-watch");
    grunt.loadNpmTasks("grunt-contrib-copy");
    grunt.loadNpmTasks("grunt-contrib-connect");
    grunt.loadNpmTasks("grunt-sync");
    return grunt.registerTask("default", ["copy", "connect:livereload", "watch"]);
  };

}).call(this);
